add_requires("sdl2")
add_requires("sdl2_image")
add_requires("openal")
add_requires("physfs")
add_requires("lua")
target("gb")
    set_kind("binary")
    add_files("src/*.c")
    add_packages("sdl2", "openal", "physfs")
    add_packages("sdl2_image")
    add_packages("lua")