name: SteamOS (Latest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: lscr.io/linuxserver/steamos:latest
      env:
        NODE_ENV: development
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies Linux
        run: >
          sudo pacman --noconfirm -Sy openal sdl2 sdl2_image lua physfs
      - name: Configure
        run: cmake .
      - name: Build
        run: >
          make
